# Generated by Django 5.2.1 on 2025-06-13 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('ddokchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='account_bank_code',
        ),
        migrations.RemoveField(
            model_name='message',
            name='account_bank_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='account_holder',
        ),
        migrations.RemoveField(
            model_name='message',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', '텍스트'), ('image', '이미지'), ('account_info', '계좌정보'), ('address_info', '주소정보')], max_length=20),
        ),
        migrations.CreateModel(
            name='AccountInfoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='거래 완료로 삭제된 정보')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='삭제된 시간', null=True)),
                ('note', models.TextField(blank=True, help_text='계좌 전송 시 메모')),
                ('bank_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='accounts.bankprofile')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_content', to='ddokchat.message')),
            ],
        ),
        migrations.CreateModel(
            name='AddressMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='거래 완료로 삭제된 정보')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='삭제된 시간', null=True)),
                ('delivery_note', models.TextField(blank=True, help_text='배송 메모 (선택사항)')),
                ('address_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='accounts.addressprofile')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_content', to='ddokchat.message')),
            ],
        ),
        migrations.CreateModel(
            name='ImageMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chat_images/')),
                ('caption', models.TextField(blank=True, help_text='이미지 설명 (선택사항)')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image_content', to='ddokchat.message')),
            ],
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='text_content', to='ddokchat.message')),
            ],
        ),
    ]
