# Generated by Django 5.2.1 on 2025-06-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemessage',
            name='image',
            field=models.ImageField(upload_to='ddokchat/images/'),
        ),
    ]
