# Generated by Django 5.2.1 on 2025-06-16 06:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ddokchat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['buyer', 'created_at'], name='ddokchat_ch_buyer_i_d36f95_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['seller', 'created_at'], name='ddokchat_ch_seller__9bb333_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['buyer_completed', 'seller_completed'], name='ddokchat_ch_buyer_c_342bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(condition=models.Q(('is_read', False)), fields=['room', 'receiver', 'is_read'], name='idx_unread_messages'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'timestamp'], name='idx_room_messages'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', '-timestamp'], name='idx_latest_message'),
        ),
    ]
