# Generated by Django 5.2.1 on 2025-06-30 01:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ddokchat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='buyer_cancel_requested',
            field=models.BooleanField(default=False, verbose_name='구매자 취소 요청'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='cancel_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='최초 취소 요청 시간'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='실제 취소 완료 시간'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='거래 취소 여부'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='seller_cancel_requested',
            field=models.BooleanField(default=False, verbose_name='판매자 취소 요청'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['is_cancelled', 'cancel_requested_at'], name='ddokchat_ch_is_canc_387fe5_idx'),
        ),
    ]
