# Generated by Django 5.2.1 on 2025-05-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
