# Generated by Django 5.2.1 on 2025-06-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokchat', '0002_chatroom_ddokchat_ch_buyer_i_d36f95_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemessage',
            name='caption',
        ),
        migrations.AddField(
            model_name='imagemessage',
            name='taken_datetime',
            field=models.DateTimeField(blank=True, help_text='촬영 날짜/시간', null=True),
        ),
    ]
