# Generated by Django 5.2.1 on 2025-06-30 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('ddokchat', '0002_chatroom_buyer_cancel_requested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', '텍스트'), ('image', '이미지'), ('bank_info', '계좌정보'), ('address_info', '주소정보')], max_length=20),
        ),
        migrations.CreateModel(
            name='BankInfoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='거래 완료로 삭제된 정보')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='삭제된 시간', null=True)),
                ('bank_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='accounts.bankprofile')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_content', to='ddokchat.message')),
            ],
        ),
        migrations.DeleteModel(
            name='AccountInfoMessage',
        ),
    ]
