# Generated by Django 5.2.1 on 2025-06-13 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddokchat', '0002_alter_message_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountinfomessage',
            name='note',
        ),
        migrations.RemoveField(
            model_name='addressmessage',
            name='delivery_note',
        ),
    ]
