# Generated by Django 5.2.1 on 2025-06-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokchat', '0002_chatroom_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='image',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
