# Generated by Django 5.2.1 on 2025-06-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokchat', '0003_remove_chatroom_image_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
