# Generated by Django 5.2.1 on 2025-06-23 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokchat', '0003_remove_imagemessage_caption_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReportEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chat_report_evidence/', verbose_name='증거 이미지')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='이미지 설명')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatRoomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fraud', '사기 및 허위 거래'), ('inappropriate_content', '부적절한 채팅 내용'), ('harassment', '욕설, 협박, 괴롭힘'), ('no_response', '연락두절, 무응답'), ('item_condition', '상품 상태 허위 설명'), ('payment_issue', '결제 관련 문제'), ('other', '기타')], max_length=30, verbose_name='신고 사유')),
                ('description', models.TextField(help_text='구체적인 신고 사유를 작성해주세요', verbose_name='신고 내용 상세')),
                ('status', models.CharField(choices=[('pending', '검토 중'), ('investigating', '조사 중'), ('resolved', '처리 완료'), ('rejected', '신고 반려')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('admin_notes', models.TextField(blank=True, verbose_name='관리자 메모')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 일시')),
                ('restriction_applied', models.BooleanField(default=False, verbose_name='제재 적용 여부')),
                ('restriction_start', models.DateTimeField(blank=True, null=True, verbose_name='제재 시작일')),
                ('restriction_end', models.DateTimeField(blank=True, null=True, verbose_name='제재 종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신고 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ddokchat.chatroom', verbose_name='채팅방')),
                ('evidence_images', models.ManyToManyField(blank=True, to='ddokchat.chatreportevidence', verbose_name='증거 이미지')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatroom_reports_processed', to=settings.AUTH_USER_MODEL, verbose_name='처리한 관리자')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_reports_received', to=settings.AUTH_USER_MODEL, verbose_name='신고 대상 유저')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom_reports_made', to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
            ],
            options={
                'verbose_name': '채팅방 신고',
                'verbose_name_plural': '채팅방 신고 목록',
                'ordering': ['-created_at'],
                'unique_together': {('reporter', 'chatroom')},
            },
        ),
    ]
