# Generated by Django 5.2.1 on 2025-06-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokchat', '0004_chatroom_is_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatroom',
            old_name='is_sold',
            new_name='buyer_completed',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='seller_completed',
            field=models.BooleanField(default=False),
        ),
    ]
