# Generated by Django 5.2.1 on 2025-06-25 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ddokchat', '0004_chatreportevidence_chatroomreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='uuid',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='room_code',
            field=models.CharField(blank=True, db_index=True, max_length=12, unique=True),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['room_code'], name='ddokchat_ch_room_co_7c05e9_idx'),
        ),
    ]
