# Generated by Django 5.2.1 on 2025-06-11 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokchat', '0006_message_account_bank_name_message_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='account_bank_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
