# Generated by Django 5.2.1 on 2025-06-23 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BdayCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_type', models.CharField(choices=[('bday', '생일'), ('debut', '데뷔일'), ('comeback', '컴백'), ('concert', '콘서트'), ('other', '기타')], default='bday', max_length=20, verbose_name='카페 유형')),
                ('cafe_name', models.CharField(max_length=100, verbose_name='카페명')),
                ('place_name', models.CharField(blank=True, max_length=100, verbose_name='장소명')),
                ('address', models.TextField(verbose_name='주소')),
                ('road_address', models.TextField(blank=True, verbose_name='도로명주소')),
                ('kakao_place_id', models.CharField(blank=True, max_length=50, verbose_name='카카오 장소 ID')),
                ('latitude', models.FloatField(verbose_name='위도')),
                ('longitude', models.FloatField(verbose_name='경도')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('special_benefits', models.TextField(blank=True, verbose_name='특전 정보')),
                ('event_description', models.TextField(blank=True, verbose_name='이벤트 설명')),
                ('image_gallery', models.JSONField(blank=True, default=list, verbose_name='이미지 갤러리')),
                ('x_source', models.URLField(blank=True, verbose_name='X 출처')),
                ('status', models.CharField(choices=[('pending', '승인 대기'), ('approved', '승인됨'), ('rejected', '거부됨'), ('expired', '만료됨')], default='pending', max_length=20, verbose_name='상태')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='승인일')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.artist', verbose_name='아티스트')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artist.member', verbose_name='멤버')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cafes', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
            ],
            options={
                'verbose_name': '생일카페',
                'verbose_name_plural': '생일카페 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CafeFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritecafes', to='ddoksang.bdaycafe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '카페 즐겨찾기',
            },
        ),
        migrations.CreateModel(
            name='CafeViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True, verbose_name='조회 시간')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddoksang.bdaycafe', verbose_name='카페')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '카페 조회 기록',
                'verbose_name_plural': '카페 조회 기록들',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bdaycafe',
            index=models.Index(fields=['latitude', 'longitude'], name='ddoksang_bd_latitud_49833f_idx'),
        ),
        migrations.AddIndex(
            model_name='bdaycafe',
            index=models.Index(fields=['start_date', 'end_date'], name='ddoksang_bd_start_d_acbb1c_idx'),
        ),
        migrations.AddIndex(
            model_name='bdaycafe',
            index=models.Index(fields=['status', 'start_date'], name='ddoksang_bd_status_dfb27d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cafefavorite',
            unique_together={('user', 'cafe')},
        ),
        migrations.AddIndex(
            model_name='cafeviewhistory',
            index=models.Index(fields=['user', '-viewed_at'], name='ddoksang_ca_user_id_3d9d06_idx'),
        ),
        migrations.AddIndex(
            model_name='cafeviewhistory',
            index=models.Index(fields=['cafe', '-viewed_at'], name='ddoksang_ca_cafe_id_2da667_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cafeviewhistory',
            unique_together={('user', 'cafe')},
        ),
    ]
