# Generated by Django 5.2.1 on 2025-06-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddoksang', '0001_initial'),
    ]

    operations = [
         migrations.AddField(
            model_name='bdaycafe',
            name='x_source',
            field=models.URLField(blank=True, verbose_name='X 출처'),
        ),
    ]
