# Generated by Django 5.2.1 on 2025-05-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddoksang', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bdaycafe',
            options={'ordering': ['-created_at'], 'verbose_name': '생일카페', 'verbose_name_plural': '생일카페 목록'},
        ),
        migrations.AlterModelOptions(
            name='tourplan',
            options={'verbose_name': '투어 플랜', 'verbose_name_plural': '투어 플랜 목록'},
        ),
        migrations.AlterModelOptions(
            name='tourstop',
            options={'ordering': ['order'], 'verbose_name': '투어 경유지', 'verbose_name_plural': '투어 경유지 목록'},
        ),
        migrations.AlterModelOptions(
            name='usersearchhistory',
            options={'ordering': ['-created_at'], 'verbose_name': '검색 기록', 'verbose_name_plural': '검색 기록 목록'},
        ),
        migrations.AlterField(
            model_name='bdaycafe',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='추천 여부'),
        ),
        migrations.AlterField(
            model_name='bdaycafe',
            name='place_url',
            field=models.URLField(blank=True, verbose_name='카카오맵 URL'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='optimized_route_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='total_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='total_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='transportation_mode',
            field=models.CharField(choices=[('TRANSIT', '대중교통'), ('CAR', '자동차'), ('WALK', '도보')], default='TRANSIT', max_length=20, verbose_name='이동 수단'),
        ),
        migrations.AlterField(
            model_name='tourstop',
            name='distance_to_next',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourstop',
            name='duration_to_next',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourstop',
            name='estimated_stay_duration',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='tourstop',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tourstop',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='tourstop',
            name='route_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersearchhistory',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersearchhistory',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersearchhistory',
            name='search_query',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='usersearchhistory',
            name='search_type',
            field=models.CharField(choices=[('keyword', '키워드'), ('location', '위치'), ('artist', '아티스트')], max_length=20),
        ),
    ]
