# Generated by Django 5.2.1 on 2025-06-04 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddoksang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafefavorite',
            name='cafe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritecafes', to='ddoksang.bdaycafe'),
        ),
    ]
