# Generated by Django 5.2.1 on 2025-06-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddoksang', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdaycafeimage',
            name='image_type',
            field=models.CharField(choices=[('main', '메인 이미지'), ('poster', '포스터')], default='other', max_length=20, verbose_name='이미지 유형'),
        ),
    ]
