# Generated by Django 5.2.1 on 2025-06-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddoksang', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdaycafe',
            name='detailed_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='상세주소'),
        ),
    ]
