# Generated by Django 5.2.1 on 2025-06-21 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddoksang', '0002_alter_bdaycafeimage_image_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now=True, verbose_name='조회 시간')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddoksang.bdaycafe', verbose_name='카페')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '카페 조회 기록',
                'verbose_name_plural': '카페 조회 기록들',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', '-viewed_at'], name='ddoksang_ca_user_id_3d9d06_idx'), models.Index(fields=['cafe', '-viewed_at'], name='ddoksang_ca_cafe_id_2da667_idx')],
                'unique_together': {('user', 'cafe')},
            },
        ),
    ]
