# Generated by Django 5.2.1 on 2025-05-29 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddoksang', '0002_alter_bdaycafe_options_alter_tourplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdaycafe',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='bday_cafes/main/', verbose_name='메인 이미지 (구버전)'),
        ),
        migrations.AlterField(
            model_name='bdaycafe',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='bday_cafes/poster/', verbose_name='포스터 이미지 (구버전)'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='optimized_route_data',
            field=models.JSONField(blank=True, null=True, verbose_name='최적화된 경로 데이터'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='total_distance',
            field=models.FloatField(blank=True, null=True, verbose_name='총 거리(km)'),
        ),
        migrations.AlterField(
            model_name='tourplan',
            name='total_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='총 소요시간(분)'),
        ),
        migrations.AlterField(
            model_name='tourstop',
            name='distance_to_next',
            field=models.FloatField(blank=True, null=True, verbose_name='다음 장소까지 거리(km)'),
        ),
        migrations.AlterField(
            model_name='tourstop',
            name='duration_to_next',
            field=models.IntegerField(blank=True, null=True, verbose_name='다음 장소까지 소요시간(분)'),
        ),
        migrations.AlterField(
            model_name='tourstop',
            name='estimated_stay_duration',
            field=models.IntegerField(default=60, verbose_name='예상 체류 시간(분)'),
        ),
        migrations.AlterField(
            model_name='tourstop',
            name='notes',
            field=models.TextField(blank=True, verbose_name='메모'),
        ),
        migrations.AlterField(
            model_name='tourstop',
            name='order',
            field=models.PositiveIntegerField(verbose_name='순서'),
        ),
        migrations.AlterField(
            model_name='tourstop',
            name='route_info',
            field=models.JSONField(blank=True, null=True, verbose_name='경로 상세 정보'),
        ),
        migrations.AlterField(
            model_name='usersearchhistory',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='검색 위치 위도'),
        ),
        migrations.AlterField(
            model_name='usersearchhistory',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='검색 위치 경도'),
        ),
        migrations.AlterField(
            model_name='usersearchhistory',
            name='search_query',
            field=models.CharField(max_length=200, verbose_name='검색어'),
        ),
        migrations.AlterField(
            model_name='usersearchhistory',
            name='search_type',
            field=models.CharField(choices=[('keyword', '키워드'), ('location', '위치'), ('artist', '아티스트')], max_length=20, verbose_name='검색 유형'),
        ),
        migrations.CreateModel(
            name='BdayCafeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bday_cafes/images/%Y/%m/', verbose_name='이미지')),
                ('image_type', models.CharField(choices=[('main', '메인 이미지'), ('poster', '포스터'), ('menu', '메뉴판'), ('interior', '내부 전경'), ('exterior', '외부 전경'), ('goods', '굿즈/특전'), ('event', '이벤트'), ('other', '기타')], default='other', max_length=20, verbose_name='이미지 유형')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='이미지 설명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('is_main', models.BooleanField(default=False, verbose_name='대표 이미지')),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='파일 크기(bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ddoksang.bdaycafe')),
            ],
            options={
                'verbose_name': '생카 이미지',
                'verbose_name_plural': '생카 이미지들',
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['cafe', 'is_main'], name='ddoksang_bd_cafe_id_65d5d7_idx'), models.Index(fields=['cafe', 'order'], name='ddoksang_bd_cafe_id_06bbd7_idx')],
            },
        ),
    ]
