# Generated by Django 5.2.1 on 2025-06-24 01:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddoksang', '0002_bdaycafe_detailed_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bdaycafe',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_cafes', to=settings.AUTH_USER_MODEL, verbose_name='찜한 사용자들'),
        ),
        migrations.DeleteModel(
            name='CafeFavorite',
        ),
    ]
