# Generated by Django 5.2.1 on 2025-06-24 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddoksang', '0003_bdaycafe_favorited_by_delete_cafefavorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CafeViewHistory',
        ),
    ]
