# Generated by Django 5.2.1 on 2025-06-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddoksang', '0003_alter_bdaycafe_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bdaycafe',
            name='place_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='실제 장소명'),
        ),
    ]
