# Generated by Django 5.2.1 on 2025-06-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddoksang', '0004_bdaycafe_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bdaycafe',
            name='place_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='장소명'),
        ),
    ]
