# Generated by Django 5.2.1 on 2025-06-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokdam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dambdaycafepost',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='damcommunitypost',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dammannerpost',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
