# Generated by Django 5.1.7 on 2025-05-21 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokdam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damcomment',
            name='bdaycafe_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ddokdam.dambdaycafepost'),
        ),
        migrations.AlterField(
            model_name='damcomment',
            name='community_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ddokdam.damcommunitypost'),
        ),
        migrations.AlterField(
            model_name='damcomment',
            name='manner_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ddokdam.dammannerpost'),
        ),
    ]
