# Generated by Django 5.1.7 on 2025-05-21 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokdam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddokdamcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ddokdam.ddokdamcomment'),
        ),
    ]
