# Generated by Django 5.1.7 on 2025-05-22 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokdam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dambdaycafepost',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='damcommunitypost',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dammannerpost',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='liked_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
    ]
