# Generated by Django 5.2.1 on 2025-05-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokdam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddokdampost',
            name='cafe_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ddokdampost',
            name='cafe_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ddokdampost',
            name='doll',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ddokdampost',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ddokdampost',
            name='hashtags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ddokdampost',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ddokdampost',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ddokdampost',
            name='idol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
