# Generated by Django 5.2.1 on 2025-06-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokdam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dambdaycafepost',
            name='linked_ddoksang_cafe_id',
            field=models.PositiveIntegerField(blank=True, help_text='덕생에 등록된 카페의 ID (수동 입력 방지를 위해 별도 관리)', null=True, verbose_name='연결된 덕생 카페 ID'),
        ),
    ]
