# Generated by Django 5.2.1 on 2025-05-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokdam', '0002_ddokdamcomment_ddokdampost_delete_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddokdampost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ddokdampost',
            name='category',
            field=models.CharField(choices=[('community', '덕담 한마디'), ('food', '예절 차리기'), ('cafe', '덕생 후기')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ddokdampost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ddokdam/'),
        ),
        migrations.AlterField(
            model_name='ddokdampost',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
