# Generated by Django 5.1.7 on 2025-05-27 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_member_followers_alter_artist_followers'),
        ('ddokdam', '0002_alter_dambdaycafepost_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dambdaycafepost',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.artist'),
        ),
        migrations.AddField(
            model_name='dambdaycafepost',
            name='members',
            field=models.ManyToManyField(blank=True, to='artist.member'),
        ),
        migrations.AddField(
            model_name='damcommunitypost',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.artist'),
        ),
        migrations.AddField(
            model_name='damcommunitypost',
            name='members',
            field=models.ManyToManyField(blank=True, to='artist.member'),
        ),
        migrations.AddField(
            model_name='dammannerpost',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.artist'),
        ),
        migrations.AddField(
            model_name='dammannerpost',
            name='members',
            field=models.ManyToManyField(blank=True, to='artist.member'),
        ),
    ]
