# Generated by Django 5.2.1 on 2025-06-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokdam', '0002_dambdaycafepost_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='damcomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
