# Generated by Django 5.2.1 on 2025-05-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokdam', '0002_ddokdamcomment_ddokdampost_delete_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddokdampost',
            name='category',
            field=models.CharField(choices=[('community', '덕담 남기기'), ('food', '예절샷으로 예절 차리기'), ('cafe', '덕생 후기 남기기')], default='community', max_length=20),
        ),
    ]
