# Generated by Django 5.2.1 on 2025-05-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokdam', '0002_ddokdampost_cafe_location_ddokdampost_cafe_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ddokdampost',
            name='like_users',
        ),
        migrations.AlterField(
            model_name='ddokdampost',
            name='idol',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
