# Generated by Django 5.1.7 on 2025-05-22 02:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokdam', '0002_alter_damcomment_bdaycafe_post_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dambdaycafepost',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='liked_bdaycafe_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='damcommunitypost',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='liked_community_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dammannerpost',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='liked_manner_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
