# Generated by Django 5.2.1 on 2025-05-17 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokdam', '0003_alter_ddokdampost_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ddokdampost',
            name='likes',
        ),
        migrations.AddField(
            model_name='ddokdampost',
            name='idol',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ddokdampost',
            name='like_users',
            field=models.ManyToManyField(blank=True, related_name='like_ddokdam_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ddokdamcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ddokdamcomment', to='ddokdam.ddokdampost'),
        ),
        migrations.AlterField(
            model_name='ddokdampost',
            name='category',
            field=models.CharField(choices=[('community', '커뮤니티'), ('food', '예절샷'), ('cafe', '생일카페')], default='community', max_length=20),
        ),
        migrations.AlterField(
            model_name='ddokdampost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ddokdam/image'),
        ),
    ]
