# Generated by Django 5.2.1 on 2025-06-19 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddokdam', '0003_userrestriction_dampostreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dampostreport',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='dampostreport',
            name='violation_level',
        ),
    ]
