# Generated by Django 5.1.7 on 2025-05-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokdam', '0003_dambdaycafepost_like_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dambdaycafepost',
            name='cafe_location',
        ),
        migrations.RemoveField(
            model_name='dambdaycafepost',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='dambdaycafepost',
            name='start_date',
        ),
        migrations.AddField(
            model_name='damcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
