# Generated by Django 5.2.1 on 2025-06-24 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddokdam', '0003_userrestriction_dampostreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrestriction',
            name='user',
        ),
        migrations.DeleteModel(
            name='DamPostReport',
        ),
        migrations.DeleteModel(
            name='UserRestriction',
        ),
    ]
