# Generated by Django 5.2.1 on 2025-06-11 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokdam', '0004_alter_damcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ddokdam.damcomment'),
        ),
    ]
