# Generated by Django 5.1.7 on 2025-05-26 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_favorite_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='MannerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')])),
                ('punctuality', models.CharField(max_length=50)),
                ('description_match', models.CharField(max_length=50)),
                ('response_speed', models.CharField(max_length=50)),
                ('politeness', models.CharField(max_length=50)),
                ('deal_again', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manner_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
