# Generated by Django 5.2.1 on 2025-06-16 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('ddokchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mannerreview',
            name='chatroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ddokchat.chatroom'),
        ),
        migrations.AddField(
            model_name='mannerreview',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mannerreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manner_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
