# Generated by Django 5.2.1 on 2025-06-17 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressprofile',
            name='_encrypted_building_name',
        ),
        migrations.RemoveField(
            model_name='addressprofile',
            name='_encrypted_jibun_address',
        ),
    ]
