# Generated by Django 5.1.7 on 2025-05-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email_alter_user_username'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_artists',
            field=models.ManyToManyField(blank=True, related_name='followers', to='artist.artist'),
        ),
    ]
