# Generated by Django 5.2.1 on 2025-06-26 00:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_is_profile_completed_and_more'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kakao_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='naver_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_signup_completed',
        ),
        migrations.RemoveField(
            model_name='user',
            name='suspension_end',
        ),
        migrations.RemoveField(
            model_name='user',
            name='suspension_reason',
        ),
        migrations.RemoveField(
            model_name='user',
            name='suspension_start',
        ),
        migrations.AlterField(
            model_name='addressprofile',
            name='_encrypted_detail_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressprofile',
            name='_encrypted_phone_number',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressprofile',
            name='_encrypted_postal_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addressprofile',
            name='_encrypted_road_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fandomprofile',
            name='applied_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fandomprofile',
            name='fandom_artist',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='artist.artist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fandomprofile',
            name='fandom_card',
            field=models.ImageField(default='', upload_to='fandom_cards/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fandomprofile',
            name='verification_end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='인증 만료일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fandomprofile',
            name='verification_start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='인증 시작일'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserSuspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspension_start', models.DateTimeField(verbose_name='제재 시작일')),
                ('suspension_end', models.DateTimeField(blank=True, null=True, verbose_name='제재 종료일')),
                ('suspension_reason', models.TextField(verbose_name='제재 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_suspension', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 제재',
                'verbose_name_plural': '사용자 제재 목록',
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('kakao', '카카오'), ('naver', '네이버'), ('google', '구글')], max_length=20, verbose_name='소셜 제공자')),
                ('social_id', models.CharField(max_length=100, verbose_name='소셜 ID')),
                ('signup_completed', models.BooleanField(default=False, verbose_name='소셜 가입 완료 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '소셜 계정',
                'verbose_name_plural': '소셜 계정 목록',
                'unique_together': {('provider', 'social_id')},
            },
        ),
    ]
