# Generated by Django 5.2.1 on 2025-06-17 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_addressprofile__encrypted_building_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressprofile',
            name='_encrypted_phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
