# Generated by Django 5.2.1 on 2025-05-28 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_bio'),
        ('artist', '0004_member_followers_alter_artist_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fandom_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.artist'),
        ),
        migrations.AddField(
            model_name='user',
            name='fandom_card',
            field=models.ImageField(blank=True, null=True, upload_to='fandom_cards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_pending_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_fandom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_failed',
            field=models.BooleanField(default=False),
        ),
    ]
