# Generated by Django 5.2.1 on 2025-06-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_addressprofile__encrypted_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='suspension_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='제재 종료일'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_reason',
            field=models.TextField(blank=True, null=True, verbose_name='제재 사유'),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='제재 시작일'),
        ),
    ]
