# Generated by Django 5.2.1 on 2025-06-09 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_fandom_artist_user_fandom_card_and_more'),
        ('ddokchat', '0005_rename_is_sold_chatroom_buyer_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mannerreview',
            name='chatroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ddokchat.chatroom'),
        ),
    ]
