# Generated by Django 5.2.1 on 2025-06-26 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_google_id_remove_user_kakao_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankprofile',
            old_name='_encrypted_account_number',
            new_name='_encrypted_bank_number',
        ),
        migrations.RenameField(
            model_name='bankprofile',
            old_name='account_holder',
            new_name='bank_holder',
        ),
    ]
