# Generated by Django 5.2.1 on 2025-06-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_mannerreview_chatroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mannerreview',
            name='punctuality',
        ),
        migrations.AlterField(
            model_name='mannerreview',
            name='deal_again',
            field=models.CharField(max_length=10, verbose_name='재거래 의사'),
        ),
        migrations.AlterField(
            model_name='mannerreview',
            name='description_match',
            field=models.CharField(max_length=50, verbose_name='상품 상태 일치 여부'),
        ),
        migrations.AlterField(
            model_name='mannerreview',
            name='politeness',
            field=models.CharField(max_length=50, verbose_name='메시지 말투'),
        ),
        migrations.AlterField(
            model_name='mannerreview',
            name='rating',
            field=models.IntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], verbose_name='전반적인 거래 만족도'),
        ),
        migrations.AlterField(
            model_name='mannerreview',
            name='response_speed',
            field=models.CharField(max_length=50, verbose_name='응답 속도'),
        ),
    ]
