# Generated by Django 5.2.1 on 2025-06-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename__encrypted_account_number_bankprofile__encrypted_bank_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerrequest',
            name='banner_image',
            field=models.ImageField(upload_to='accounts/user_banners/', verbose_name='배너 이미지'),
        ),
        migrations.AlterField(
            model_name='fandomprofile',
            name='fandom_card',
            field=models.ImageField(upload_to='accounts/fandom_cards/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(upload_to='accounts/profile_images/'),
        ),
    ]
