# Generated by Django 5.2.1 on 2025-06-26 08:51

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='https://oddoke-bucket.s3.ap-northeast-2.amazonaws.com/default/profile.png', null=True, upload_to=accounts.models.profile_image_upload),
        ),
    ]
