# Generated by Django 5.2.1 on 2025-06-19 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_suspension_end_user_suspension_reason_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('profanity', '욕설, 불쾌한 표현 사용'), ('hate_spam', '혐오 발언, 반복적 광고, 선정적 내용'), ('illegal', '불법 콘텐츠, 범죄, 개인정보 노출'), ('irrelevant', '관련성이 낮은 게시글')], max_length=20, verbose_name='신고 사유')),
                ('additional_info', models.TextField(blank=True, verbose_name='추가 설명')),
                ('status', models.CharField(choices=[('pending', '검토 중'), ('approved', '신고 승인'), ('rejected', '신고 반려'), ('resolved', '처리 완료')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('admin_notes', models.TextField(blank=True, verbose_name='관리자 메모')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 일시')),
                ('restriction_start', models.DateTimeField(blank=True, null=True, verbose_name='제재 시작일')),
                ('restriction_end', models.DateTimeField(blank=True, null=True, verbose_name='제재 종료일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신고 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_processed', to=settings.AUTH_USER_MODEL, verbose_name='처리한 관리자')),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='신고 대상 유저')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL, verbose_name='신고자')),
            ],
            options={
                'verbose_name': '게시글 신고',
                'verbose_name_plural': '게시글 신고 목록',
                'ordering': ['-created_at'],
                'unique_together': {('reporter', 'content_type', 'object_id')},
            },
        ),
    ]
