# Generated by Django 5.2.1 on 2025-06-20 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_postreport'),
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DdokPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='총 보유 똑')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근 변동 일시')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ddok_point', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '똑 포인트',
                'verbose_name_plural': '똑 포인트 목록',
            },
        ),
        migrations.CreateModel(
            name='DdokPointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_change', models.IntegerField(verbose_name='변동된 똑')),
                ('reason', models.CharField(choices=[('BIRTHDAY_GAME', '생일시 맞추기'), ('EVENT_PARTICIPATION', '이벤트 참여'), ('POST_REWARD', '게시글 작성 보상')], max_length=50, verbose_name='변동 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='기록 일시')),
                ('point_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='accounts.ddokpoint', verbose_name='포인트 소유자')),
                ('related_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.member', verbose_name='관련 멤버')),
            ],
            options={
                'verbose_name': '똑 포인트 로그',
                'verbose_name_plural': '똑 포인트 로그 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
