# Generated by Django 5.2.1 on 2025-06-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_mannerreview_punctuality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_holder',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='예금주명'),
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='계좌번호'),
        ),
        migrations.AddField(
            model_name='user',
            name='account_registered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='계좌 등록일'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='은행 코드'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='은행명'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_account_verified',
            field=models.BooleanField(default=False, verbose_name='계좌 인증 여부'),
        ),
    ]
