# Generated by Django 5.2.1 on 2025-06-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_account_holder_user_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_completed',
            field=models.BooleanField(default=False, verbose_name='프로필 완성 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_temp_username',
            field=models.BooleanField(default=False, verbose_name='임시 사용자명 여부'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_signup_completed',
            field=models.BooleanField(default=False, verbose_name='소셜 가입 완료 여부'),
        ),
    ]
