# Generated by Django 5.2.1 on 2025-06-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_ddokpoint_ddokpointlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ddokpoint',
            options={'verbose_name': '덕 포인트', 'verbose_name_plural': '덕 포인트 목록'},
        ),
        migrations.AlterModelOptions(
            name='ddokpointlog',
            options={'ordering': ['-created_at'], 'verbose_name': '덕 포인트 로그', 'verbose_name_plural': '덕덕 포인트 로그 목록'},
        ),
        migrations.AlterField(
            model_name='ddokpoint',
            name='total_points',
            field=models.PositiveIntegerField(default=0, verbose_name='쌓인 덕'),
        ),
        migrations.AlterField(
            model_name='ddokpointlog',
            name='points_change',
            field=models.IntegerField(verbose_name='변동된 덕'),
        ),
    ]
