# Generated by Django 5.2.1 on 2025-06-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_profile_completed_user_is_temp_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='카카오 ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='naver_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='네이버 ID'),
        ),
    ]
