# Generated by Django 5.2.1 on 2025-06-24 07:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_ddokpoint_options_alter_ddokpointlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ddokpointlog',
            name='reason',
            field=models.CharField(choices=[('BIRTHDAY_GAME', '생일시 맞추기'), ('EVENT_PARTICIPATION', '이벤트 참여'), ('POST_REWARD', '게시글 작성 보상'), ('BANNER_REQUEST', '배너 신청'), ('BANNER_REFUND', '배너 신청 환불')], max_length=50, verbose_name='변동 사유'),
        ),
        migrations.CreateModel(
            name='BannerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=100, verbose_name='아티스트명')),
                ('banner_image', models.ImageField(upload_to='user_banners/', verbose_name='배너 이미지')),
                ('ddok_points_used', models.PositiveIntegerField(default=1000, verbose_name='사용된 덕 포인트')),
                ('status', models.CharField(choices=[('pending', '승인 대기'), ('approved', '승인됨'), ('rejected', '거절됨'), ('expired', '만료됨')], default='pending', max_length=20, verbose_name='상태')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인 일시')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='만료 일시')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='거절 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_banners', to=settings.AUTH_USER_MODEL, verbose_name='승인자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_requests', to=settings.AUTH_USER_MODEL, verbose_name='신청자')),
            ],
            options={
                'verbose_name': '배너 신청',
                'verbose_name_plural': '배너 신청 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
