# Generated by Django 5.2.1 on 2025-06-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_ddokpoint_options_alter_ddokpointlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='구글 ID'),
        ),
    ]
