# Generated by Django 5.2.1 on 2025-06-24 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_ddokpointlog_reason_bannerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddokpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성 일시'),
            preserve_default=False,
        ),
    ]
