# Generated by Django 5.2.1 on 2025-06-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_ddokpoint_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='배너 종료일'),
        ),
        migrations.AddField(
            model_name='bannerrequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 상태'),
        ),
        migrations.AddField(
            model_name='bannerrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='배너 시작일'),
        ),
    ]
