# Generated by Django 5.2.1 on 2025-06-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_google_id'),
        ('accounts', '0012_bannerrequest_end_date_bannerrequest_is_active_and_more'),
    ]

    operations = [
    ]
