# Generated by Django 5.2.1 on 2025-06-02 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0005_artist_fandom'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ddokfarm/image')),
                ('object_id', models.PositiveIntegerField()),
                ('is_representative', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='FarmRentalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('md', models.CharField(choices=[('poca', '포토카드'), ('md', 'MD'), ('light_stick', '응원봉'), ('album', '앨범'), ('etc', '기타')], max_length=20)),
                ('condition', models.CharField(choices=[('new', '미개봉'), ('almost_new', '거의 새것'), ('used', '사용감 있음'), ('damaged', '하자 있음')], max_length=20)),
                ('shipping', models.CharField(choices=[('delivery', '택배'), ('direct', '직거래'), ('both', '직거래, 택배')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('want_to', models.CharField(choices=[('sell', '빌려줍니다'), ('buy', '빌려주세요')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.artist')),
                ('like', models.ManyToManyField(blank=True, related_name='liked_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, to='artist.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmSellPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('md', models.CharField(choices=[('poca', '포토카드'), ('md', 'MD'), ('light_stick', '응원봉'), ('album', '앨범'), ('etc', '기타')], max_length=20)),
                ('condition', models.CharField(choices=[('new', '미개봉'), ('almost_new', '거의 새것'), ('used', '사용감 있음'), ('damaged', '하자 있음')], max_length=20)),
                ('shipping', models.CharField(choices=[('delivery', '택배'), ('direct', '직거래'), ('both', '직거래, 택배')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('want_to', models.CharField(choices=[('sell', '팝니다'), ('buy', '삽니다'), ('exchange', '교환해요')], max_length=20)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.artist')),
                ('like', models.ManyToManyField(blank=True, related_name='liked_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, to='artist.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmSplitPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('album', models.CharField(choices=[('include', '포함'), ('not_include', '미포함')], max_length=20)),
                ('opened', models.CharField(choices=[('opende', '개봉'), ('unopened', '미개봉')], max_length=20)),
                ('shipping_fee', models.PositiveIntegerField()),
                ('where', models.CharField(max_length=100)),
                ('when', models.DateField()),
                ('failure', models.CharField(choices=[('failure', '무산'), ('not_failure', '무산없음'), ('split', 'N빵')], max_length=20)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.artist')),
                ('like', models.ManyToManyField(blank=True, related_name='liked_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, to='artist.member')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ddokfarm.farmcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rental_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ddokfarm.farmrentalpost')),
                ('sell_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ddokfarm.farmsellpost')),
                ('split_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ddokfarm.farmsplitpost')),
            ],
        ),
    ]
