# Generated by Django 5.1.7 on 2025-05-22 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmRentalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='ddokfarm/image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('new', '새상품'), ('almost_new', '거의 새것'), ('used', '중고'), ('damaged', '손상있음')], default='new', max_length=20)),
                ('shipping', models.CharField(choices=[('direct', '직거래'), ('delivery', '택배'), ('both', '직거래, 택배')], default='both', max_length=20)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('like', models.ManyToManyField(blank=True, related_name='liked_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmSellPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='ddokfarm/image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('condition', models.CharField(choices=[('new', '새상품'), ('almost_new', '거의 새것'), ('used', '중고'), ('damaged', '손상있음')], default='new', max_length=20)),
                ('shipping', models.CharField(choices=[('direct', '직거래'), ('delivery', '택배'), ('both', '직거래, 택배')], default='both', max_length=20)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('is_sold', models.BooleanField(default=False)),
                ('want_to', models.CharField(choices=[('sell', '팝니다'), ('buy', '삽니다'), ('exchange', '교환해요')], default='new', max_length=20)),
                ('like', models.ManyToManyField(blank=True, related_name='liked_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmSplitPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='ddokfarm/image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.BooleanField(default=False)),
                ('opened', models.BooleanField(default=False)),
                ('shipping_fee', models.PositiveIntegerField()),
                ('where', models.CharField(max_length=100)),
                ('when', models.CharField(max_length=100)),
                ('failure', models.TextField(blank=True)),
                ('like', models.ManyToManyField(blank=True, related_name='liked_%(class)s', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='ddokfarm.farmcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rental_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ddokfarm.farmrentalpost')),
                ('sell_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ddokfarm.farmsellpost')),
                ('split_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ddokfarm.farmsplitpost')),
            ],
        ),
    ]
