# Generated by Django 5.2.1 on 2025-06-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmpostimage',
            name='image',
            field=models.ImageField(help_text='덕팜 게시글 이미지', upload_to='ddokfarm/images/'),
        ),
    ]
