# Generated by Django 5.2.1 on 2025-06-02 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_artist_fandom'),
        ('ddokfarm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmsplitpost',
            name='members',
        ),
        migrations.CreateModel(
            name='SplitPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.member')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_prices', to='ddokfarm.farmsplitpost')),
            ],
            options={
                'unique_together': {('post', 'member')},
            },
        ),
    ]
