# Generated by Django 5.2.1 on 2025-06-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprice',
            name='is_price_undetermined',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemprice',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
