# Generated by Django 5.1.7 on 2025-05-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmrentalpost',
            name='want_to',
            field=models.CharField(choices=[('sell', '빌려줍니다'), ('buy', '빌려주세요')], default='new', max_length=20),
        ),
    ]
