# Generated by Django 5.1.7 on 2025-05-22 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ddokfarmpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ddokfarmpost',
            name='image',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
