# Generated by Django 5.2.1 on 2025-06-20 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('ddokfarm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmrentalpost',
            name='md',
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('item_name', models.CharField(blank=True, help_text="물건명 (비어있으면 '덕N'으로 자동 표시)", max_length=20)),
                ('price', models.PositiveIntegerField(help_text='개별 물건 가격')),
                ('is_sold', models.BooleanField(default=False, help_text='개별 판매 완료 여부 (향후 기능)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
