# Generated by Django 5.2.1 on 2025-05-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmpostimage',
            name='is_representative',
            field=models.BooleanField(default=False),
        ),
    ]
