# Generated by Django 5.2.1 on 2025-06-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_artist_fandom'),
        ('ddokfarm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmsplitpost',
            name='checked_out_members',
            field=models.ManyToManyField(blank=True, related_name='checked_out_split_posts', to='artist.member'),
        ),
    ]
