# Generated by Django 5.2.1 on 2025-05-30 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmrentalpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='farmsellpost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='farmsplitpost',
            name='image',
        ),
        migrations.CreateModel(
            name='FarmPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ddokfarm/image')),
                ('rental_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ddokfarm.farmrentalpost')),
                ('sell_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ddokfarm.farmsellpost')),
                ('split_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ddokfarm.farmsplitpost')),
            ],
        ),
    ]
