# Generated by Django 5.2.1 on 2025-06-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0002_alter_farmpostimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmpostimage',
            name='image',
            field=models.ImageField(upload_to='ddokfarm/images/'),
        ),
    ]
