# Generated by Django 5.1.7 on 2025-05-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0002_farmrentalpost_want_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmsplitpost',
            name='failure',
            field=models.CharField(choices=[('failure', '무산'), ('not_failure', '무산없음'), ('split', 'N빵')], default='failure', max_length=20),
        ),
    ]
