# Generated by Django 5.2.1 on 2025-06-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0002_remove_farmrentalpost_md_itemprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmrentalpost',
            name='price',
        ),
        migrations.RemoveField(
            model_name='farmsellpost',
            name='price',
        ),
    ]
