# Generated by Django 5.2.1 on 2025-05-16 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('new', '새상품'), ('almost_new', '거의 새것'), ('used', '중고'), ('damaged', '손상있음')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='exchange',
            field=models.CharField(choices=[('possible', '교환가능'), ('impossible', '교환불가')], default='impossible', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='shipping',
            field=models.CharField(choices=[('direct', '직거래'), ('delivery', '택배'), ('both', '직거래, 택배')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ddokfarm.category'),
        ),
    ]
