# Generated by Django 5.2.1 on 2025-05-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0003_category_post_condition_post_exchange_post_is_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='direct_deal',
            field=models.CharField(choices=[('possible', '가능'), ('impossible', '불가능')], default='impossible', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='preferred_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
