# Generated by Django 5.2.1 on 2025-06-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0003_remove_farmrentalpost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmrentalpost',
            name='shipping_fee',
            field=models.PositiveIntegerField(blank=True, help_text='배송비 (원)', null=True),
        ),
        migrations.AddField(
            model_name='farmrentalpost',
            name='shipping_methods',
            field=models.CharField(blank=True, help_text='선택된 배송 방법들 (콤마로 구분)', max_length=200),
        ),
        migrations.AddField(
            model_name='farmsellpost',
            name='shipping_fee',
            field=models.PositiveIntegerField(blank=True, help_text='배송비 (원)', null=True),
        ),
        migrations.AddField(
            model_name='farmsellpost',
            name='shipping_methods',
            field=models.CharField(blank=True, help_text='선택된 배송 방법들 (콤마로 구분)', max_length=200),
        ),
        migrations.AddField(
            model_name='farmsplitpost',
            name='shipping_methods',
            field=models.CharField(blank=True, help_text='선택된 배송 방법들 (콤마로 구분)', max_length=200),
        ),
        migrations.AlterField(
            model_name='farmsplitpost',
            name='shipping_fee',
            field=models.PositiveIntegerField(blank=True, help_text='배송비 (원)', null=True),
        ),
    ]
