# Generated by Django 5.1.7 on 2025-05-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0003_alter_farmsplitpost_failure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmsplitpost',
            name='album',
            field=models.CharField(choices=[('include', '포함'), ('not_include', '미포함')], default='include', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmsplitpost',
            name='opened',
            field=models.CharField(choices=[('opende', '개봉'), ('unopened', '미개봉')], default='unopened', max_length=20),
        ),
    ]
