# Generated by Django 5.2.1 on 2025-06-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0003_splitapplication'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='splitapplication',
            unique_together=set(),
        ),
    ]
