# Generated by Django 5.2.1 on 2025-06-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0004_alter_splitapplication_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmsplitpost',
            name='push',
            field=models.CharField(choices=[('include', '포함'), ('not_include', '미포함')], default='yes', max_length=20),
            preserve_default=False,
        ),
    ]
