# Generated by Django 5.1.7 on 2025-05-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0004_alter_farmsplitpost_album_alter_farmsplitpost_opened'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmsplitpost',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
