# Generated by Django 5.2.1 on 2025-06-23 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0004_farmrentalpost_shipping_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprice',
            name='is_price_undetermined',
            field=models.BooleanField(default=False, help_text='가격 미정 여부'),
        ),
        migrations.CreateModel(
            name='ExchangeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('give_description', models.TextField(help_text='내가 주는 것', verbose_name='주는 것')),
                ('want_description', models.TextField(help_text='내가 받고 싶은 것', verbose_name='받고 싶은 것')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_info', to='ddokfarm.farmsellpost')),
            ],
            options={
                'verbose_name': '교환 정보',
                'verbose_name_plural': '교환 정보',
                'ordering': ['id'],
            },
        ),
    ]
