# Generated by Django 5.1.7 on 2025-05-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0005_farmsplitpost_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmrentalpost',
            name='condition',
            field=models.CharField(choices=[('new', '미개봉'), ('almost_new', '거의 새것'), ('used', '사용감 있음'), ('damaged', '하자 있음')], max_length=20),
        ),
        migrations.AlterField(
            model_name='farmrentalpost',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='farmrentalpost',
            name='shipping',
            field=models.CharField(choices=[('delivery', '택배'), ('direct', '직거래'), ('both', '직거래, 택배')], max_length=20),
        ),
        migrations.AlterField(
            model_name='farmrentalpost',
            name='want_to',
            field=models.CharField(choices=[('sell', '빌려줍니다'), ('buy', '빌려주세요')], max_length=20),
        ),
        migrations.AlterField(
            model_name='farmsellpost',
            name='condition',
            field=models.CharField(choices=[('new', '미개봉'), ('almost_new', '거의 새것'), ('used', '사용감 있음'), ('damaged', '하자 있음')], max_length=20),
        ),
        migrations.AlterField(
            model_name='farmsellpost',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='farmsellpost',
            name='shipping',
            field=models.CharField(choices=[('delivery', '택배'), ('direct', '직거래'), ('both', '직거래, 택배')], max_length=20),
        ),
        migrations.AlterField(
            model_name='farmsellpost',
            name='want_to',
            field=models.CharField(choices=[('sell', '팝니다'), ('buy', '삽니다'), ('exchange', '교환해요')], max_length=20),
        ),
        migrations.AlterField(
            model_name='farmsplitpost',
            name='album',
            field=models.CharField(choices=[('include', '포함'), ('not_include', '미포함')], max_length=20),
        ),
        migrations.AlterField(
            model_name='farmsplitpost',
            name='failure',
            field=models.CharField(choices=[('failure', '무산'), ('not_failure', '무산없음'), ('split', 'N빵')], max_length=20),
        ),
        migrations.AlterField(
            model_name='farmsplitpost',
            name='opened',
            field=models.CharField(choices=[('opende', '개봉'), ('unopened', '미개봉')], max_length=20),
        ),
    ]
