# Generated by Django 5.2.1 on 2025-06-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0005_itemprice_is_price_undetermined_exchangeitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeitem',
            name='give_description',
            field=models.CharField(help_text='내가 주는 것', max_length=50, verbose_name='주는 것'),
        ),
        migrations.AlterField(
            model_name='exchangeitem',
            name='want_description',
            field=models.CharField(help_text='내가 받고 싶은 것', max_length=50, verbose_name='받고 싶은 것'),
        ),
    ]
