# Generated by Django 5.2.1 on 2025-06-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0005_farmsplitpost_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmsplitpost',
            name='push',
            field=models.CharField(choices=[('yes', '가능'), ('no', '불가능')], max_length=20),
        ),
    ]
