# Generated by Django 5.1.7 on 2025-05-26 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0006_alter_farmrentalpost_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmsplitpost',
            name='when',
            field=models.DateField(),
        ),
    ]
