# Generated by Django 5.2.1 on 2025-06-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0006_alter_farmsplitpost_push'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmrentalpost',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmsellpost',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='farmsplitpost',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
