# Generated by Django 5.1.7 on 2025-05-27 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_member_followers_alter_artist_followers'),
        ('ddokfarm', '0007_alter_farmsplitpost_when'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmrentalpost',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.artist'),
        ),
        migrations.AddField(
            model_name='farmrentalpost',
            name='members',
            field=models.ManyToManyField(blank=True, to='artist.member'),
        ),
        migrations.AddField(
            model_name='farmsellpost',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.artist'),
        ),
        migrations.AddField(
            model_name='farmsellpost',
            name='members',
            field=models.ManyToManyField(blank=True, to='artist.member'),
        ),
        migrations.AddField(
            model_name='farmsplitpost',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='artist.artist'),
        ),
        migrations.AddField(
            model_name='farmsplitpost',
            name='members',
            field=models.ManyToManyField(blank=True, to='artist.member'),
        ),
    ]
