# Generated by Django 5.2.1 on 2025-06-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0007_farmrentalpost_view_count_farmsellpost_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmcomment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
