# Generated by Django 5.2.1 on 2025-06-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddokfarm', '0008_farmcomment_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='ddokfarm.farmcomment'),
        ),
    ]
