# Generated by Django 5.1.7 on 2025-05-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='유저에게 보여줄 대표 이름', max_length=100, unique=True)),
                ('korean_name', models.CharField(blank=True, help_text='한글명', max_length=100, null=True)),
                ('english_name', models.CharField(blank=True, help_text='영문명', max_length=100, null=True)),
                ('alias', models.CharField(blank=True, help_text='줄임말 또는 별칭', max_length=100, null=True)),
            ],
        ),
    ]
