# Generated by Django 5.2.1 on 2025-06-26 06:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='유저에게 보여줄 대표 이름', max_length=100, unique=True)),
                ('korean_name', models.CharField(blank=True, help_text='한글명', max_length=100, null=True)),
                ('english_name', models.CharField(blank=True, help_text='영문명', max_length=100, null=True)),
                ('alias', models.CharField(blank=True, help_text='줄임말 또는 별칭', max_length=100, null=True)),
                ('logo', models.CharField(blank=True, help_text='static/image 경로 기준', max_length=255, null=True)),
                ('fandom', models.CharField(blank=True, max_length=100, null=True)),
                ('is_solo', models.BooleanField(default=False, help_text='솔로 아티스트인지 여부')),
                ('followers', models.ManyToManyField(blank=True, related_name='favorite_artists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=100)),
                ('member_bday', models.CharField(blank=True, max_length=10, null=True)),
                ('artist_name', models.ManyToManyField(related_name='members', to='artist.artist')),
                ('followers', models.ManyToManyField(blank=True, related_name='favorite_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
