# Generated by Django 5.1.7 on 2025-05-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_solo',
            field=models.BooleanField(default=False, help_text='솔로 아티스트인지 여부'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='멤버 이름', max_length=100)),
                ('bday', models.DateField(blank=True, help_text='생년월일', null=True)),
                ('groups', models.ManyToManyField(help_text='소속 그룹/유닛', related_name='members', to='artist.artist')),
            ],
        ),
    ]
