# Generated by Django 4.2.10 on 2025-05-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='is_active',
        ),
        migrations.AddField(
            model_name='artist',
            name='alias',
            field=models.CharField(blank=True, help_text='줄임말 또는 별칭', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='english_name',
            field=models.CharField(blank=True, help_text='영문명', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='is_solo',
            field=models.BooleanField(default=False, help_text='솔로 아티스트인지 여부'),
        ),
        migrations.AddField(
            model_name='artist',
            name='korean_name',
            field=models.CharField(blank=True, help_text='한글명', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='logo',
            field=models.CharField(blank=True, help_text='static/image 경로 기준', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
