# Generated by Django 4.2.10 on 2025-05-22 08:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artist', '0002_remove_artist_is_active_artist_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='favourite_artists', to=settings.AUTH_USER_MODEL),
        ),
    ]
