# Generated by Django 5.1.7 on 2025-05-26 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_artist_followers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='favorite_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artist',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='favorite_artists', to=settings.AUTH_USER_MODEL),
        ),
    ]
