# Generated by Django 5.2.1 on 2025-05-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_member_followers_alter_artist_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='fandom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
