# Generated by Django 5.2.1 on 2025-06-12 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('comment', '댓글'), ('reply', '대댓글'), ('chat', '채팅'), ('split_application', '분철 참여 신청'), ('split_approved', '분철 승인'), ('split_rejected', '분철 반려'), ('like', '좋아요'), ('follow', '팔로우')], max_length=20, verbose_name='알림 유형')),
                ('object_id', models.PositiveIntegerField()),
                ('message', models.TextField(verbose_name='알림 메시지')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='알림 발생 사용자')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='알림 받을 사용자')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'notification_type', 'content_type', 'object_id'], name='notificatio_recipie_b0efba_idx')],
            },
        ),
    ]
