# Generated by Django 5.2.1 on 2025-06-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('comment', '댓글'), ('reply', '대댓글'), ('post_reply', '게시글 답글'), ('chat', '채팅'), ('split_application', '분철 참여 신청'), ('split_approved', '분철 승인'), ('split_rejected', '분철 반려'), ('like', '좋아요'), ('follow', '팔로우'), ('cafe_approved', '생일카페 승인'), ('cafe_rejected', '생일카페 반려'), ('fandom_verified', '팬덤 인증 승인'), ('fandom_rejected', '팬덤 인증 반려'), ('trade_complete_request', '거래완료 요청')], max_length=25, verbose_name='알림 유형'),
        ),
    ]
