# Generated by Django 5.2.1 on 2025-06-24 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_sender_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='마지막 발신자'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_count',
            field=models.PositiveIntegerField(default=1, verbose_name='메시지 개수'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'),
        ),
    ]
